name: Java CI with Maven

on:
  push:
    branches: [ main, Dev ]
  pull_request:
    branches: [ main, Dev ]

jobs:
  test:
    runs-on: ${{ matrix.os-version }}
    strategy:
      matrix:
        os-version: [windows-latest, ubuntu-latest, macOS-latest]
        java-version: [17.x]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        java-version: ${{ matrix.java-version }}
        cache: maven
        distribution: 'temurin'
    - name: Use  ${{ matrix.os-version }}
      uses: actions/setup-java@v2
      with:
        java-version: ${{ matrix.java-version }}
        distribution: 'temurin'
    - name: Build
      run: |
        docker-compose up -d
        mvn install
      env:
        CI: true
