name: Docker Image CI

on:
  push:
    branches: [ main, Dev ]
  pull_request:
    branches: [ main, Dev ]

jobs:

  build:

    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/Dev'
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image    
      working-directory: ./front
      run: docker build . --tag front
