name: Docker Image CI

on:
  push:
    branches: [ main, Dev ]
  pull_request:
    branches: [ main, Dev ]

jobs:

  build:

    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/Dev'
    steps:
    - uses: actions/checkout@v2
    - name: build front docker image  
      working-directory: ./front
      run: docker build . --tag front
    - name: maven
      working-directory: ./api
      run: mvn package -DskipTests
    - name: build api docker image
      working-directory: ./api
      run: docker build -f src/main/docker/Dockerfile.jvm -t quarkus/code-with-quarkus-jvm .
    - name: Deploy to Docker Host
      uses: wshihadeh/docker-deployment-action@v1
      with:        
        deployment_mode: docker-compose
        args: up -d
        docker_prune: 'true'
        pull_images_first: 'true'